### ISSUE TITLE
Config option for a list of users to not collect logs for

### ISSUE THREAD

**Issue by Leppunen** [gempir/justlog#104]
If a user wishes to opt out from log collection it would be good to have a option for this.

**Comment by gempir** [comment]
Should probably also disallow requesting any previous logs for that user, right?

**Comment by Leppunen** [comment]
perhaps, atleast requesting directly unless removing from channel logs is feasible during parsing. i have a script to remove user lines from channel logs with sed if need arises, but it's not super efficient for obvious reasons

**Comment by gempir** [comment]
Done in f9eeebd03739b21c46d8907fd2655de15a89bba2 

I won't be doing any deletion, I think that is too risky. Most users probably have a bigger issue about the logs being so readily accessible via the website. Reading channel logs and finding the user line by line requires a lot more work for a bad actor to read logs.

**Comment by LeetHaxor** [comment]
How do I use this feature? I've noticed quite a few randoms with no logs so I'm assuming anyone can do it?

**Comment by gempir** [comment]
Only admins of the instance are able to optout users

**Comment by LeetHaxor** [comment]
> Only admins of the instance are able to optout users

Forgive my ignorance, but what does that mean exactly?

**Comment by gempir** [comment]
If you want your messages not be available or recorded anymore you need to contact an admin of the instance which you don't want to collect logs of you.

**Comment by LeetHaxor** [comment]
> If you want your messages not be available or recorded anymore you need to contact an admin of the instance which you don't want to collect logs of you.

Ah ok so only admins can do it. 

What exactly does "instance" refer to in regards to Twitch? I'm not really familiar with the term in this context. Thanks for the answers.

**Comment by gempir** [comment]
This is an open source software. Anyone can download and run it. And the instances are independent so the settings are not synced across them.

I don't even run the biggest instance for example

**Comment by LeetHaxor** [comment]
> This is an open source software. Anyone can download and run it. And the instances are independent so the settings are not synced across them.
> 
> I don't even run the biggest instance for example

Makes sense, thanks for explaining. Much appreciated.
