### ISSUE TITLE
Add redirect endpoint for last existing logs

### ISSUE THREAD

**Issue by RAnders00** [gempir/justlog#12]
When visiting `/channels/:channel/user/:user`, it redirects to the current year and month currently. I am suggesting a different endpoint (maybe `/last`) or to change the redirect behaviour so it directs to the last month the user typed, e.g. when calling that endpoint in January 2019 and the user's last log line was in November 2018, the endpoint would redirect to `/channels/:channel/user/:user/2018/11`.

**Comment by gempir** [comment]
Makes sense, I have thought about this already a bit before and definetly want it.

Although I think without specifying the month and year I will just redirect to the last logs. No /last endpoint

**Comment by gempir** [comment]
Done!
