### ISSUE TITLE
Allow channels to be added without downtime

### ISSUE THREAD

**Issue by RAnders00** [gempir/justlog#14]
This could be solved by two ways:

1) Make a seamless deploy system
2) Allow the bot to join a new channel (and save the channel to the config) during runtime, using a chat command (e.g. `!justlogjoin channelName`)

or both! :)

**Comment by gempir** [comment]
This is the relevant part for deploys 

https://github.com/gempir/justlog/blob/19f95d3424bf4bbf476d5739c23ffc099bc25870/Makefile#L12

**Comment by gempir** [comment]
Alright, I'm using rsync now and only restarting after rsync is done. Works great now and the downtime is maybe 1-2seconds MAX.
