### ISSUE TITLE
Compiling and using Go binary no longer works

### ISSUE THREAD

**Issue by Fijxu** [gempir/justlog#142]
I have always used justlog by building the Go binary and running it instead of using docker, but now it doesn't work anymore leaving only the `gitkeep` directory visible.

![image](https://user-images.githubusercontent.com/61166695/147618217-465660ed-08fe-4376-b093-f30c131d8a5a.png)

The last commit in which the Go binary worked is 84acc65f6e01cfe4561d645132139ac7a8f0c05e

**Comment by gempir** [comment]
You now need to build the web assets beforehand. `cd web && yarn && yarn-build`
