### ISSUE TITLE
Opted out users are not removed from the `/channels` endpoint

### ISSUE THREAD

**Issue by brian6932** [gempir/justlog#165]
For example in https://logs.ivr.fi/channels
userID: `137199626` name: `kattah` is still there, despite being opted out of the service

**Comment by gempir** [comment]
Any future messages will not appear anymore, but it would be extremely expensive to clear them from old channel logs.

**Comment by brian6932** [comment]
That's fair, but at the same time, displaying an opted out user's login and uid in an endpoint meant to show usable channels the api has to offer feels wrong tbh, even if the logs were not cleared.
Would it not be possible to just filter out opted out users in the `/channels` endpoint? It's not like those channels are user accessible.

**Comment by gempir** [comment]
Oh I misunderstood the original issue. 

I think this is too niche of a usecase. The user originally opted into being logged. At least that's my intention for justlog to be used. You don't just randomly add channels to it. 

In this case kattah should just be removed from the ivr.fi instance "manually"
