### ISSUE TITLE
Opting out

### ISSUE THREAD

**Issue by savannahpm** [gempir/justlog#169]
I used the program and received error "user or channel has opted out". I do not see that as an option & would like to know how to opt out.

**Comment by gempir** [comment]
Contact an admin of the instance you want to opt out from.

**Comment by savannahpm** [comment]
Where do I find admins of https://logs.ivr.fi/?

**Comment by gempir** [comment]
@savannahpm Just this weekend, I implemented a feature that allows you to opt out yourself without admin help. 

Checkout this page https://logs.ivr.fi/?optout=
