### ISSUE TITLE
Timestamp different from Normal Site and Raw Site

### ISSUE THREAD

**Issue by lucas19961** [gempir/justlog#172]
How can i Change the Time? The Logs server use the UTC time but the main server is on Timezone Europe/Berlin 
![opera_mjIPQiPP08](https://user-images.githubusercontent.com/17136546/184462931-2f0642ee-283b-4b43-a719-d13f63610416.png)
![opera_cw4Y9BZ06f](https://user-images.githubusercontent.com/17136546/184462953-42118f0b-cdbc-44f6-9023-e9f2af26dc42.png)

**Comment by gempir** [comment]
The web UI uses your browser locale to determine timezone.

https://day.js.org/docs/en/timezone/guessing-user-timezone
