### ISSUE TITLE
[Feature request] Endpoint for listing log files for channel 

### ISSUE THREAD

**Issue by Mm2PL** [gempir/justlog#173]
I'd like to be able to enumerate channel logs for [justgrep](https://github.com/mm2pl/justgrep). The current way I do this is very inideal, I basically hit every possible file in sequence until i hit a 404 error. 

I'd like for the /list endpoint to be extended to list logs for a certain channel but not user.

**Comment by gempir** [comment]
Okay so you mean something like 

`/list?channel=nymn`

And it lists 
```
{
    "availableLogs": [
        {
            "year": "2022",
            "month": "8",
            "day": "1"
        },
        {
            "year": "2016",
            "month": "4",
            "day": "31"
        }
    ]
}
```

**Comment by Mm2PL** [comment]
Yep basically.

14 sie 2022 11:15:01 gempir ***@***.***>:
