### ISSUE TITLE
Bug: Twitch Suspended users return a list of 100's of empty months

### ISSUE THREAD

**Issue by hotbear1110** [gempir/justlog#180]
If I try to look up a twitch suspended user, I would expect to get an error, but instead I get a giant list of months with no logs in them...

Here is how it looks: 
![image](https://user-images.githubusercontent.com/77441913/201061191-a94e8c4e-c6cf-4d59-b65a-e5a38e070540.png)

https://logs.ivr.fi/?channel=nymn&username=drdisrespect

**Comment by gempir** [comment]
That didn't do it yet.

**Comment by gempir** [comment]
completely fixed in 2998fbd28a709aef09d228782ed0b1b90e86f807
