### ISSUE TITLE
[Feature Request] Search option “go-to”

### ISSUE THREAD

**Issue by Florian2807** [gempir/justlog#182]
An additional search option “go-to” just like cmd+f would be cool to read the context of chat-messages

**Comment by gempir** [comment]
You can actually go into twitch chat mode and then Ctrl + F, because it has no lazy loading

**Comment by Florian2807** [comment]
Oh yeah, never used this feature looks pretty scuffed xd

But thank you :)

**Comment by gempir** [comment]
I forgot that feature existed as well. It's not super well maintained, but it kinda works and It's better than writing an entire new feature.
