### ISSUE TITLE
DB Logging

### ISSUE THREAD

**Issue by viomck** [gempir/justlog#193]
A file log is great for ease of use, but a database is ideal for a larger-scale implementation.  I was wondering if you had any plans to do so, and, if not, if you'd be willing to accept a PR that implements this functionality.

**Comment by gempir** [comment]
Not happening. A database is not ideal for larger-scale implementations if you want to stay cheap.
Justlog was always about storing logs easily and without too many scaling issues.

I've had Mysql, Cassandra, Redis, Elasticsearch experiments before. In the end plain files are a lot easier to scale.

Read more about the history of me writing a log bot.
https://gempir.com/blog/logs/

**Comment by gempir** [comment]
But nothing stops you from re-using parts of justlog to do so. There have been some efforts to make that easier https://github.com/gempir/justlog/pull/178

**Comment by viomck** [comment]
I do not see how a configurable disabled-by-default database implementation harms your software at all, but OK

**Comment by gempir** [comment]
Who is going to maintain that implementation?

What if there is a security issue in the DB library? --> Who makes the updates?
What about compatibility to future database versions?
What about compatibility to other databases?
What if I want to change my implementation heavily and now I have to test that the database implementation still works. 

Like I said, I suggest you create a fork and implement it there.
