### ISSUE TITLE
`channel/:channelName/range` returns weird/incorrect time ranges

### ISSUE THREAD

**Issue by RAnders00** [gempir/justlog#28]
E.g. see: https://logs.ivr.fi/channel/pajlada/range

Returned are messages from `2019-06-27` and `2019-07-27` so this is basically `[now, now - 24h] ∪ [now - 30d, now - 31d]` when it (I'm guessing) really should only show the last 24 hours.

**Comment by gempir** [comment]
Yea, idk what I was thinking here https://github.com/gempir/justlog/blob/d9577b693765b81c177cb2188fa5e970b3719cc0/api/channel.go#L178

**Comment by gempir** [comment]
Range is now removed just pass from and/or to and it should give out the correct logs
