### ISSUE TITLE
FFZ emotes broken

### ISSUE THREAD

**Issue by Felanbird** [gempir/justlog#59]
* global ffz (just incase)
* channel ffz emote
* bttv emote
* sub emote

![image](https://user-images.githubusercontent.com/41973452/91839918-daf64200-ec1d-11ea-8d9b-e0b97f64c446.png)

**Comment by gempir** [comment]
Title is confusing. Is everything broken?

**Comment by gempir** [comment]
The List is a description for the image below, that confused me at first. 

FFZ and FFZ Global Emotes are broken

**Comment by gempir** [comment]
Fixed in 30f8d063fd2e5dbf4751900479517901625ae516
