### ISSUE TITLE
API support for changing messageType logging

### ISSUE THREAD

**Issue by Felanbird** [gempir/justlog#62]
so there would be capability for an api request to disable mod action logging just before a large amount of bans is executed, and then re-enabling it once the bans are done

just the api verison of manually typing
>!justlog messageType channelname 1
>!justlog messageType channelname reset

**Comment by gempir** [comment]
Done in f5ca76b59e326bbecacc322c0ff0dda143622a6f

**Comment by gempir** [comment]
I will also add a DELETE endpoint to reset the setting

**Comment by gempir** [comment]
Delete implemented in 7e92a8bb48ea55f6362510d8e904503a4267f28c
