### ISSUE TITLE
/channel/{channelName}/user/{userName} route does not work if both {channelName} and {userName} contain non-lowercase characters

### ISSUE THREAD

**Issue by pajlada** [gempir/justlog#63]
Example of URLs that do not work:
https://logs.ivr.fi/channel/Pajlada/user/Pajlada/2020/9 (Mixed case channelName, Mixed case userName)

Example of URLs that do work:
https://logs.ivr.fi/channel/Pajlada/user/pajlada/2020/9 (Mixed case channelName, lower case userName)
https://logs.ivr.fi/channel/pajlada/user/Pajlada/2020/9 (Lower case channelName, mixed case userName)
https://logs.ivr.fi/channel/pajlada/user/pajlada/2020/9 (Lower case channelName, lower case userName)

**Comment by gempir** [comment]
fixed in 291b765
