### ISSUE TITLE
Allow managing channels via API

### ISSUE THREAD

**Issue by Mm2PL** [gempir/justlog#68]
I would like to have API endpoints for adding and removing channels from Justlog.

# Proposed interface
## Adding channels
`POST /admin/channels/?id=...&id=...&id=...`
Would add channels identified by `id`s into the config

## Removing channels
`DELETE /admin/channels/?id=...&id=...&id=...`
Would delete channels identified by `id`s from the config, but not their logs.

**Comment by gempir** [comment]
Done in https://github.com/gempir/justlog/pull/70
