### ISSUE TITLE
Browser find function doesn't work after frontend refactor

### ISSUE THREAD

**Issue by TETYYS** [gempir/justlog#79]
Only finds things that currently in view, even only for one month

**Comment by gempir** [comment]
Hmm. Might have to add a real search to fix this. Will have to look into it.

Meanwhile you can disable performance mode in the settings to go back to the old view.

**Comment by gempir** [comment]
Added a search in 834f8b7348ef04eb82c4627f0c152c677d67fcf1 it doesn't work over the whole site. Idk how important that is to you.
