### ISSUE TITLE
Link to specific part of user's logs

### ISSUE THREAD

**Issue by pajlada** [gempir/justlog#8]
I would like to be able to link to a specific part of a users log

Use case:
 - Moderator goes to my bot's dashboard, looks up moderation actions for a user and sees who timed the user out. Dashboard example https://i.imgur.com/O8xkJ9S.png
 - The moderator wants to know why the user was timed out, so he needs log contexts.
 - If I could I have a "logs" button next to each moderation action that would link to your logs at the time he got timed out, that would be pretty neat

Parameters I can imagine sending:
 - Channel ID, User ID, Timestamp in UTC

If it's easier, I would only be interested in messages before the timestamp. but getting more messages below it wouldn't be an issue, as long as it can be marked out properly where the last message before the timestamp exists

**Comment by gempir** [comment]
Here is a demo version of it:

https://justlog.gempir.com/channel/pajlada/user/gempir/range?from=1543708800&to=1543795200

Not sure if justlog will be the final API URL, but the rest will probably be the same. 

As an alternative you can also call it with userids.

https://justlog.gempir.com/channelid/11148817/userid/77829817/range?from=1543708800&to=1543795200


There are some rules to this: 
- without any parameters it will default to -1 current month to time.Now() (you can leave out either parameter and just pass the other aswell)
- 1 month is the query limit so, anything over 30/31 days will just be limited to 30/31 days

If you care how this really works here is the code: https://github.com/gempir/justlog/blob/master/api/server.go#L130

I'm working on a full API documentation with the likes of swagger or so, for testing this should be good.

**Comment by pajlada** [comment]
From a glance this looks perfect, I will try to integrate this into my testing and see how it turns out.
