### ISSUE TITLE
Raw logs button unable to support id: searching

### ISSUE THREAD

**Issue by Felanbird** [gempir/justlog#81]
direct url while mousing over the button
![image](https://user-images.githubusercontent.com/41973452/100427095-ebbd2500-305f-11eb-8a7b-e4086c0b2e32.png)

url returned once clicking the button
![image](https://user-images.githubusercontent.com/41973452/100427238-2e7efd00-3060-11eb-83e5-6ca3c9964781.png)

**Comment by RAnders00** [comment]
Has been foxed by https://github.com/gempir/justlog/commit/9cf5017758f4ae31040b55bfe7facf1e36d2ea0d
