### ISSUE TITLE
Incorrect message rendering 

### ISSUE THREAD

**Issue by zneix** [gempir/justlog#88]
Sometimes logs are still being rendered incorrectly. I assume it's because that's a USERNOTICE message, not a PRIVMSG
Example: https://logs.ivr.fi/?channel=forsen&username=xqcow
Text version: https://logs.ivr.fi/channel/forsen/user/xqcow/2021/1?raw

**Comment by gempir** [comment]
Fixed in #549c1976fed414926eecaa87fdd82948243983ee
