### ISSUE TITLE
parse `from` and `to` epoch windows for channel request correctly

### ISSUE THREAD

**Issue by chuckxD** [gempir/justlog#89]
Currently from/to epoch params are failing as a time span is too big error. See any request kinda like this http://localhost:8025/channel/hotpoopsandcooldudes/2021/2/12?from=1613112699369&to=1613116253136

I dunno the Go Duration stuff is pretty dank and probably a source of the problem. I hard coded the things, ... (channelHourLimit, from, to, and the to minus from calc/conversion to hours comparison against the channel limit and was able to get the from/to hourly window to work for this request.

Here's my SHA https://github.com/chuckxD/justlog/commit/1306cfd25444c246157a74efae7b70029294e5b7 

It's kinda noisy for a small change but figured I'd let whomever chew on it since it's quick fix for what I needed

**Comment by gempir** [comment]
Don't exactly understand your issue here. The Limit is there to prevent abuse, since requesting a very long timespan would lead to a lot of files needing to be parsed and a very big response.

**Comment by chuckxD** [comment]
Okay I was passing in ms from, to window not seconds from, to window. Maybe I misunderstood the from, to params as ms instead of seconds. `time.Unix` takes seconds not milliseconds.
