### ISSUE TITLE
Question regarding API "to" and "from"

### ISSUE THREAD

**Issue by lay295** [gempir/justlog#90]
First off, thanks for the awesome website and software :) has saved me a few times when I needed some chat logs. 

A question though, I understand that there is a 24 hour per file limit, and that it seems the API limits it to a max of 1 file read? For example, I wanted to download the whole chat log of a VOD that is 7 hours long that just happens to cross into the next day so I don't get the full chat log.

https://logs.ivr.fi/channel/moonmoon/2021/2/22?from=1613517896&to=1613545345

It's easy enough to just change my from timestamp to 1613520000 to get the rest of the logs, I was just wondering if this was intended or was a bug.

**Comment by gempir** [comment]
This is intended. There is no file limit to read, although that might be a good idea, hasn't been a problem so far though.

The limit is only determined by time.
