### ISSUE TITLE
Docker Container stops randomly

### ISSUE THREAD

**Issue by dabenzel** [gempir/justlog#96]
Hey, like your Tool!
The docker container stops every now and then. 
Last Log Message:
`time="2021-04-08T06:55:29Z" level=fatal msg="dial tcp: lookup irc.chat.twitch.tv on 10.1.1.1:53: read udp 172.17.0.13:54853->10.1.1.1:53: i/o timeout"`

Would be nice if the bot tries to reconnect automatically after a timeout and not just kill itself

**Comment by gempir** [comment]
Hmm. This is more of an go-twitch-irc issue, the Library I use to connect. 

https://github.com/gempir/go-twitch-irc/blob/2ffb3958f61a48f355e20b1c5b8eb6778e4a1742/client.go#L687

This is the logic we use to connect/reconnect, maybe this can be improved

**Comment by dabenzel** [comment]
I'm not familiar with GO. 

I've workaround'ed with docker-parameters `--restart=unless-stopped`

**Comment by gempir** [comment]
I added the restart to the README as a "quick fix" and opened an issue on go-twitch-irc to maybe improve this logic https://github.com/gempir/go-twitch-irc/issues/156

**Comment by 12932** [comment]
Interesting how it's a UDP timeout on port 53.. sounds like DNS is broken in your environment
